spring:
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backpacker_db
    username: user
    password: 123
    continueOnError: true
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #  storage size configuration
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
multipart:
  enable: true

#  storage directory
storage: media_directory

# Security
jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecret
  expiration: 72000
#  expiration: 36000