# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: backpacker_db
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "8081:80"
    depends_on:
      - db